[book]
title = "Xử lý ảnh & Thị giác máy tính"
authors = ["Nguyễn Phồn Lữa"]
language = "en"

[output.html]
additional-css = ["theme/custom.css"]
theme = "theme"
additional-js = ["theme/fix_colab_links.js"]

[output.html.search]
enable = false

[output.html.print]
enable = false
