[book]
title = "Xử lý ảnh & Thị giác máy tính"
authors = ["Nguyễn Phồn Lữa"]
language = "en"

[output.html]
additional-css = ["custom.css"]
theme = "theme"

[output.html.search]
enable = false

[output.html.print]
enable = false
