[project]
name = "xla_tgmt"
version = "0.1.0"
description = "Computer Vision and Machine Learning experiments"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "jupytext>=1.19.5",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "opencv-contrib-python>=5.0.0.93",
    "opencv-python>=5.0.0.93",
    "pandas>=3.0.5",
    "scikit-image>=0.26.0",
    "scikit-learn>=1.9.1",
]